# Generated by Django 6.0.2 on 2026-02-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponível'), ('Despachado', 'Despachado')], default='Disponivel', max_length=20),
        ),
    ]
